SELECT
    SAMPLE_ID,
    DNA_SEQUENCE,
    SPECIES,
    DNA_SEQUENCE LIKE "ATG%" AS HAS_START,
    DNA_SEQUENCE REGEXP "(TAA|TAG|TGA)$" AS HAS_STOP,
    DNA_SEQUENCE LIKE "%ATAT%" AS HAS_ATAT,
    DNA_SEQUENCE LIKE "%GGG%" AS HAS_GGG
FROM SAMPLES
ORDER BY SAMPLE_ID ASC